'use strict';

/**
 * Compliance export pack (R9) — turns a programme + its delivery records into
 * a printable, buyer-ready "readiness pack": programme terms, batch
 * traceability, quality evidence, self-assessed checklist aligned to
 * international standards (Codex GAP basics, GlobalG.A.P.-style checkpoints,
 * WOAH welfare for livestock). Honest framing: self-declared, not certified.
 */

const KB = require('./knowledge');

const STANDARD_CHECKLIST = [
  { code: 'TR1', label: 'Batch code assigned and traceable to field/unit and dates', std: 'Traceability (Codex/GlobalG.A.P.)' },
  { code: 'FS1', label: 'Water used for post-harvest handling is clean/safe', std: 'Food safety (Codex GAP)' },
  { code: 'FS2', label: 'Harvest containers clean; produce kept off the ground', std: 'Food safety (Codex GAP)' },
  { code: 'FS3', label: 'Pre-harvest intervals respected for any crop inputs', std: 'Residue control (Codex/GlobalG.A.P.)' },
  { code: 'FS4', label: 'No visibly diseased/mouldy produce in the lot (aflatoxin care)', std: 'Food safety (Codex)' },
  { code: 'LA1', label: 'Labour practices fair; no child labour; workers have water & sanitation', std: 'Ethical trade (GlobalG.A.P. GRASP-style)' },
  { code: 'EN1', label: 'Records kept of treatments applied (what/when/dose)', std: 'Environmental & record keeping' },
  { code: 'WL1', label: 'Animal handling humane (space, water, calm handling) — livestock only', std: 'WOAH welfare' },
  { code: 'Q1', label: 'Graded against the buyer specs in the programme', std: 'Quality management' },
];

function buildPack({ program, producer, deliveries, notes }) {
  const kbHints = KB.entries.filter((e) => program && program.product && e.id && programPlaybookRefs(program).includes(e.id))
    .map((e) => ({ id: e.id, title: e.title }));

  return {
    generatedAt: new Date().toISOString(),
    programme: program
      ? {
          id: program.id,
          orgName: program.orgName,
          title: program.title,
          product: program.product,
          volume: program.volume,
          qualitySpecs: program.qualitySpecs,
          priceFormula: program.priceFormula,
          deliveryWindow: program.deliveryWindow,
        }
      : null,
    producer: producer || { name: '', contact: '' },
    deliveries: (deliveries || []).map((d) => ({
      date: d.date,
      qty: d.qty,
      unit: d.unit || '',
      quality: d.quality || '',
      batchCode: d.batchCode || '',
      notes: d.notes || '',
    })),
    checklist: STANDARD_CHECKLIST.map((c) => ({ ...c, status: 'self-assessed — confirm with evidence' })),
    knowledgeHints: kbHints,
    notes: notes || '',
    disclaimer:
      'This pack is a SELF-DECLARED readiness summary generated by AgriSphere as a documentation aid. ' +
      'It is NOT a certificate. Official certification (e.g. GlobalG.A.P., organic, phytosanitary) requires ' +
      'audits by accredited bodies and national authorities.',
  };
}

function programPlaybookRefs(program) {
  // light re-use: pull kb hints from the product playbook when available
  try {
    const pb = require('./programs').playbookFor(program.product);
    return pb.kb || [];
  } catch (_) { return []; }
}

function renderHtml(pack) {
  const esc = (s) => String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const rows = (pack.checklist || []).map((c) => `<tr><td>${esc(c.code)}</td><td>${esc(c.label)}</td><td>${esc(c.std)}</td></tr>`).join('');
  const dels = (pack.deliveries || []).map((d) =>
    `<tr><td>${esc(d.date)}</td><td>${esc(d.batchCode)}</td><td>${esc(d.qty)} ${esc(d.unit)}</td><td>${esc(d.quality)}</td></tr>`).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Compliance pack — ${esc(pack.producer.name || '')}</title>
<style>body{font-family:system-ui,sans-serif;max-width:820px;margin:2rem auto;padding:0 1rem;color:#1c2b21}
h1{color:#14532d}h2{color:#166534;border-bottom:2px solid #dcfce7;padding-bottom:.2rem}
table{border-collapse:collapse;width:100%;font-size:.9rem}td,th{border:1px solid #cfe6d4;padding:.4rem .5rem;text-align:left}
th{background:#f0fdf4}.fine{color:#5b6f62;font-size:.8rem}@media print{body{margin:0}}</style></head><body>
<h1>🌾 Compliance & delivery readiness pack</h1>
<p class="fine">Generated ${esc(pack.generatedAt)} by AgriSphere · ${esc(pack.disclaimer)}</p>
<h2>1 · Programme</h2><p>${esc(pack.programme ? pack.programme.orgName + ' — ' + pack.programme.title : '—')}</p>
<table><tr><th>Product</th><td>${esc(pack.programme ? pack.programme.product : '')}</td></tr>
<tr><th>Volume</th><td>${esc(pack.programme ? pack.programme.volume : '')}</td></tr>
<tr><th>Quality specs</th><td>${esc(pack.programme ? pack.programme.qualitySpecs : '')}</td></tr>
<tr><th>Price formula</th><td>${esc(pack.programme ? pack.programme.priceFormula : '')}</td></tr></table>
<h2>2 · Producer</h2><p>${esc(pack.producer.name)} · ${esc(pack.producer.contact)}</p>
<h2>3 · Deliveries & batch records</h2>
<table><tr><th>Date</th><th>Batch</th><th>Qty</th><th>Quality note</th></tr>${dels || '<tr><td colspan="4">No deliveries recorded yet.</td></tr>'}</table>
<h2>4 · Self-assessed checklist (international practice)</h2>
<table><tr><th>#</th><th>Checkpoint</th><th>Standard</th></tr>${rows}</table>
${pack.notes ? `<h2>5 · Notes</h2><p>${esc(pack.notes)}</p>` : ''}
<p class="fine">Guidance topics: ${(pack.knowledgeHints || []).map((k) => esc(k.title)).join(' · ') || '—'}</p>
</body></html>`;
}

module.exports = { buildPack, renderHtml, STANDARD_CHECKLIST };
