'use strict';

/**
 * Compliance export pack (R9) — turns a programme + its delivery records into
 * a printable, buyer-ready "readiness pack": programme terms, batch
 * traceability, quality evidence, self-assessed checklist aligned to
 * international standards (Codex GAP basics, GlobalG.A.P.-style checkpoints,
 * WOAH welfare for livestock). Honest framing: self-declared, not certified.
 */

const KB = require('./knowledge');

const STANDARD_CHECKLIST = [
  { code: 'TR1', label: 'Batch code assigned and traceable to field/unit and dates', std: 'Traceability (Codex/GlobalG.A.P.)' },
  { code: 'FS1', label: 'Water used for post-harvest handling is clean/safe', std: 'Food safety (Codex GAP)' },
  { code: 'FS2', label: 'Harvest containers clean; produce kept off the ground', std: 'Food safety (Codex GAP)' },
  { code: 'FS3', label: 'Pre-harvest intervals respected for any crop inputs', std: 'Residue control (Codex/GlobalG.A.P.)' },
  { code: 'FS4', label: 'No visibly diseased/mouldy produce in the lot (aflatoxin care)', std: 'Food safety (Codex)' },
  { code: 'LA1', label: 'Labour practices fair; no child labour; workers have water & sanitation', std: 'Ethical trade (GlobalG.A.P. GRASP-style)' },
  { code: 'EN1', label: 'Records kept of treatments applied (what/when/dose)', std: 'Environmental & record keeping' },
  { code: 'WL1', label: 'Animal handling humane (space, water, calm handling) — livestock only', std: 'WOAH welfare' },
  { code: 'Q1', label: 'Graded against the buyer specs in the programme', std: 'Quality management' },
  // Export-readiness (where the buyer sells into regulated markets):
  { code: 'EX1', label: 'Geolocation recorded for holding/ranch and linked to each export lot (EU deforestation due-diligence readiness for cattle/beef chains)', std: 'EUDR (EU) 2023/1115 & (EU) 2025/2650 — applies from Dec 2026' },
  { code: 'EX2', label: 'Optional, buyer-required: certification-readiness for faith-sensitive export markets (Gulf/Asia orders) and food-safety schemes (e.g. BRCGS) — audits only via accredited certifiers', std: 'Market-access certification (accredited bodies)' },
];

function buildPack({ program, producer, deliveries, notes }) {
  const kbHints = KB.entries.filter((e) => program && program.product && e.id && programPlaybookRefs(program).includes(e.id))
    .map((e) => ({ id: e.id, title: e.title }));

  return {
    generatedAt: new Date().toISOString(),
    programme: program
      ? {
          id: program.id,
          orgName: program.orgName,
          title: program.title,
          product: program.product,
          volume: program.volume,
          qualitySpecs: program.qualitySpecs,
          priceFormula: program.priceFormula,
          deliveryWindow: program.deliveryWindow,
        }
      : null,
    producer: producer || { name: '', contact: '' },
    deliveries: (deliveries || []).map((d) => ({
      date: d.date,
      qty: d.qty,
      unit: d.unit || '',
      quality: d.quality || '',
      batchCode: d.batchCode || '',
      notes: d.notes || '',
      image: d.image || '',
    })),
    checklist: STANDARD_CHECKLIST.map((c) => ({ ...c, status: 'self-assessed — confirm with evidence' })),
    knowledgeHints: kbHints,
    notes: notes || '',
    disclaimer:
      'This pack is a SELF-DECLARED readiness summary generated by AgriSphere as a documentation aid. ' +
      'It is NOT a certificate. Official certification (e.g. GlobalG.A.P., organic, phytosanitary) requires ' +
      'audits by accredited bodies and national authorities.',
  };
}

function programPlaybookRefs(program) {
  // light re-use: pull kb hints from the product playbook when available
  try {
    const pb = require('./programs').playbookFor(program.product);
    return pb.kb || [];
  } catch (_) { return []; }
}

/** R16 — settlement statement (document layer only). AgriSphere never
 *  handles money: this printable statement records what the parties agreed,
 *  the delivery manifest and the settlement note for their own records. */
function buildSettlementStatement({ program, deliveries, settlement, disputes }) {
  const qtyText = (d) => `${d.qty || '?'}${d.unit ? ' ' + d.unit : ''}`;
  return {
    generatedAt: new Date().toISOString(),
    programme: program
      ? {
          id: program.id,
          orgName: program.orgName,
          title: program.title,
          product: program.product,
          volume: program.volume,
          priceFormula: program.priceFormula,
          advancePct: program.advancePct || '',
          deliveryWindow: program.deliveryWindow || '',
          status: program.status,
        }
      : null,
    deliveries: (deliveries || []).map((d) => ({
      date: d.date, qtyText: qtyText(d), batchCode: d.batchCode || '',
      quality: d.quality || '', notes: d.notes || '', image: d.image || '',
    })),
    settlement: settlement || null,
    disputeCount: (disputes || []).length,
    disputesResolved: (disputes || []).filter((d) => d.status === 'resolved').length,
    disclaimer:
      'This statement is a documentation aid generated by AgriSphere. AgriSphere does not handle money and is not a party to the contract. Keep it with the written contract and any bank/mobile-money records. For payment disputes, both parties should seek the channel agreed in their contract or a licensed mediator.',
  };
}

function renderStatementHtml(st) {
  const esc = (x) => String(x || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const rows = (st.deliveries || []).map((d) =>
    '<tr><td>' + esc(d.date) + '</td><td>' + esc(d.batchCode) + '</td><td>' + esc(d.qtyText) + '</td><td>' + esc(d.quality) +
    '</td>' + (d.image
      ? '<td><a href="' + esc(d.image) + '" target="_blank" rel="noopener"><img src="' + esc(d.image) + '" alt="delivery evidence" width="70" style="border-radius:6px;" /></a></td>'
      : '<td></td>') + '</tr>').join('');
  const prog = st.programme || {};
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Settlement statement — ${esc(prog.orgName)}</title>
<style>body{font-family:system-ui,sans-serif;max-width:820px;margin:2rem auto;padding:0 1rem;color:#1c2b21}
h1{color:#14532d}h2{color:#166534;border-bottom:2px solid #dcfce7;padding-bottom:.2rem}
table{border-collapse:collapse;width:100%;font-size:.9rem}td,th{border:1px solid #cfe6d4;padding:.4rem .5rem;text-align:left}
th{background:#f0fdf4}.fine{color:#5b6f62;font-size:.8rem}.amt{font-size:1.2rem;font-weight:800;color:#14532d}
@media print{body{margin:0}}</style></head><body>
<h1>🤝 Programme settlement statement</h1>
<p class="fine">Generated ${esc(st.generatedAt)} · ${esc(st.disclaimer)}</p>
<h2>1 · Programme</h2>
<table><tr><th>Buyer / organisation</th><td>${esc(prog.orgName)}</td></tr>
<tr><th>Programme</th><td>${esc(prog.title)}</td></tr>
<tr><th>Product</th><td>${esc(prog.product)}</td></tr>
<tr><th>Volume agreed</th><td>${esc(prog.volume)}</td></tr>
<tr><th>Price formula (written)</th><td>${esc(prog.priceFormula)}</td></tr>
${prog.advancePct ? `<tr><th>Advance / input terms</th><td>${esc(prog.advancePct)}</td></tr>` : ''}
${prog.deliveryWindow ? `<tr><th>Delivery window</th><td>${esc(prog.deliveryWindow)}</td></tr>` : ''}</table>
<h2>2 · Delivery manifest (batch records)</h2>
<table><tr><th>Date</th><th>Batch code</th><th>Quantity</th><th>Quality note</th><th>Evidence</th></tr>
${rows || '<tr><td colspan="5">No deliveries recorded.</td></tr>'}</table>
<h2>3 · Settlement record</h2>
${st.settlement
  ? `<table><tr><th>Amount</th><td class="amt">${esc(st.settlement.amount)}</td></tr>
<tr><th>Method</th><td>${esc(st.settlement.method)}</td></tr>
${st.settlement.reference ? `<tr><th>Reference</th><td>${esc(st.settlement.reference)}</td></tr>` : ''}
${st.settlement.date ? `<tr><th>Date</th><td>${esc(st.settlement.date)}</td></tr>` : ''}</table>`
  : '<p>Not settled yet — this statement is a running record until the parties record the final payment.</p>'}
<h2>4 · Dispute trail</h2>
<p>${st.disputeCount} dispute(s) raised, ${st.disputesResolved} resolved. Dispute details stay in the programme record (owner/admin view).</p>
<p class="fine">Not a tax invoice. Buyers issuing formal invoices should use their own VAT/INV numbering per Botswana requirements.</p>
</body></html>`;
}

function renderHtml(pack) {
  const esc = (s) => String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const rows = (pack.checklist || []).map((c) => `<tr><td>${esc(c.code)}</td><td>${esc(c.label)}</td><td>${esc(c.std)}</td></tr>`).join('');
  const dels = (pack.deliveries || []).map((d) =>
    `<tr><td>${esc(d.date)}</td><td>${esc(d.batchCode)}</td><td>${esc(d.qty)} ${esc(d.unit)}</td><td>${esc(d.quality)}</td></tr>`).join('');
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Compliance pack — ${esc(pack.producer.name || '')}</title>
<style>body{font-family:system-ui,sans-serif;max-width:820px;margin:2rem auto;padding:0 1rem;color:#1c2b21}
h1{color:#14532d}h2{color:#166534;border-bottom:2px solid #dcfce7;padding-bottom:.2rem}
table{border-collapse:collapse;width:100%;font-size:.9rem}td,th{border:1px solid #cfe6d4;padding:.4rem .5rem;text-align:left}
th{background:#f0fdf4}.fine{color:#5b6f62;font-size:.8rem}@media print{body{margin:0}}</style></head><body>
<h1>🌾 Compliance & delivery readiness pack</h1>
<p class="fine">Generated ${esc(pack.generatedAt)} by AgriSphere · ${esc(pack.disclaimer)}</p>
<h2>1 · Programme</h2><p>${esc(pack.programme ? pack.programme.orgName + ' — ' + pack.programme.title : '—')}</p>
<table><tr><th>Product</th><td>${esc(pack.programme ? pack.programme.product : '')}</td></tr>
<tr><th>Volume</th><td>${esc(pack.programme ? pack.programme.volume : '')}</td></tr>
<tr><th>Quality specs</th><td>${esc(pack.programme ? pack.programme.qualitySpecs : '')}</td></tr>
<tr><th>Price formula</th><td>${esc(pack.programme ? pack.programme.priceFormula : '')}</td></tr></table>
<h2>2 · Producer</h2><p>${esc(pack.producer.name)} · ${esc(pack.producer.contact)}</p>
<h2>3 · Deliveries & batch records</h2>
<table><tr><th>Date</th><th>Batch</th><th>Qty</th><th>Quality note</th></tr>${dels || '<tr><td colspan="4">No deliveries recorded yet.</td></tr>'}</table>
<h2>4 · Self-assessed checklist (international practice)</h2>
<table><tr><th>#</th><th>Checkpoint</th><th>Standard</th></tr>${rows}</table>
${pack.notes ? `<h2>5 · Notes</h2><p>${esc(pack.notes)}</p>` : ''}
<p class="fine">Guidance topics: ${(pack.knowledgeHints || []).map((k) => esc(k.title)).join(' · ') || '—'}</p>
</body></html>`;
}

module.exports = { buildPack, renderHtml, STANDARD_CHECKLIST, buildSettlementStatement, renderStatementHtml };
